image: skvorl/beremiz-requirements

pipelines:
  custom: # Pipelines that are triggered manually
    checks: # The name that is displayed in the list in the Bitbucket Cloud GUI
        - step:
            script: # Modify the commands below to build your repository.
              - python --version
              - ./tests/tools/check_source.sh
              - /usr/bin/python ./tests/tools/test_application.py

  default:
    - step:
        script: # Modify the commands below to build your repository.
          - python --version
          - ./tests/tools/check_source.sh
          - /usr/bin/python ./tests/tools/test_application.py
